name: Isabelle Build

on:
  workflow_dispatch:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Cache Isabelle Heaps
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-Isabelle2022-${{ hashFiles('ROOT') }}-${{ github.run_id }}
        path: .heaps
        restore-keys: |
          ${{ runner.os }}-Isabelle2022-${{ hashFiles('ROOT') }}
      
    - name: Build Sessions
      uses: BraeWebb/isabelle-action@v1.11
      with:
        args: "build -b -P site -D . -v"
        heapCacheDir: .heaps
        
    - name: Check State
      run: ls -R .

    - name: Setup ID
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Upload Documents
      uses: actions/upload-artifact@v2
      with:
        name: veriopt-docs-${{ steps.vars.outputs.sha_short }}
        path: |
          ./site/veriopt/**/document.pdf
          ./site/veriopt/**/outline.pdf
        
    - name: Upload HTML
      uses: actions/upload-artifact@v2
      with:
        name: veriopt-${{ steps.vars.outputs.sha_short }}
        path: ./site/veriopt
      
    - name: Deploy Main
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./site/veriopt
